### ISSUE TITLE
problems in pretrained model

### ISSUE THREAD

**Issue by Silliam** [vincent-thevenin/Realistic-Neural-Talking-Head-Models#25] opened 2019-10-12 13:38 UTC
Thanks for your pretrained model on Google Drive. I download it but failed to unzip it. The decompression software fialed to unzip it, Dose any one meet this problem?

**Comment by vincent-thevenin** [comment] 2019-10-17 05:58
Hi Silliam,
Duplicate of #23 
No need to unzip the file, it will be read and written to with the .tar extension.

**Closed by vincent-thevenin** 2019-10-17 05:58 UTC

**Comment by Silliam** [comment] 2019-10-17 07:12
Thanks a lot !




------------------ 原始邮件 ------------------
发件人: "Vincent Thévenin"<notifications@github.com>;
发送时间: 2019年10月17日(星期四) 中午1:58
收件人: "vincent-thevenin/Realistic-Neural-Talking-Head-Models"<Realistic-Neural-Talking-Head-Models@noreply.github.com>;
抄送: "Silliam"<185485516@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vincent-thevenin/Realistic-Neural-Talking-Head-Models] problemsin pretrained model (#25)




Hi Silliam,
 Duplicate of #23
 No need to unzip the file, it will be read and written to with the .tar extension.
